/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Configurazione centralizzata del progetto. Letto direttamente da scripts/deploy.sh (bash), dal backend ASP.NET Core (AddJsonFile) e dal frontend Node SSR (readFileSync). Modificare questo file e rieseguire il deploy è sufficiente per applicare la configurazione a tutti i livelli.
 */
export interface GlobalSettings {
  $schema?: string;
  /**
   * Nota descrittiva libera (ignorata dal runtime). Usata in testa ai file per ricordare a cosa serve ciascuno.
   */
  _nota?: string;
  /**
   * Identità dell'app — fonte unica. Nome e versione vivono SOLO qui: scripts/deploy.sh li slugifica per il nome progetto Docker e li passa come build ARG; il frontend li riceve iniettati in environment.ts (navbar, titolo, manifest PWA, meta app-version, rilevamento aggiornamenti).
   */
  project?: {
    /**
     * Nome visualizzato dell'app. Mostrato in navbar/titolo/manifest e slugificato per COMPOSE_PROJECT_NAME (es. 'Mercatino App' → 'mercatino-app').
     */
    name?: string;
    /**
     * Versione dell'app (es. '1.2.0'). Propagata nel meta app-version e nel manifest; usata da VersionCheckService per rilevare gli aggiornamenti.
     */
    version?: string;
    /**
     * Data di ultima modifica dei contenuti, formato italiano GG/MM/AAAA. Alimenta il <lastmod> della sitemap e og:updated_time. Bumpala a mano quando i contenuti cambiano davvero. Se assente/non valida, il build usa la data odierna.
     */
    lastModified?: string;
  };
  /**
   * Configurazione del container frontend (Angular SSR + Node). Letta da scripts/deploy.sh per le variabili docker-compose.
   */
  frontend?: {
    /**
     * Dominio pubblico del sito senza schema (es. 'miodominio.it'). Usato per FRONTEND_BASE_URL, NG_ALLOWED_HOSTS e per derivare Security.CorsOrigins. Se vuoto, il frontend Node SSR accetta solo gli host locali (localhost, 127.0.0.1, [::1]): fail-closed, così in produzione senza hostname il traffico reale viene rifiutato (421) invece di accettare qualsiasi Host. Valorizzarlo (o impostare NG_ALLOWED_HOSTS) per servire il dominio reale.
     */
    hostname?: string;
    /**
     * Porta esposta dal container frontend sull'host Docker. La porta interna del container Node SSR è sempre 3000; questa è la porta del mapping host:container.
     */
    port?: number;
    /**
     * Percorso del file con i fatti dell'installazione (hosting, CDN, reverse proxy, log del server), relativo alla cartella di global-settings.json o assoluto (es. '../hosting.json'). Un file per server, condiviso dai siti che ci girano; schema in frontend/src/app/core/engine/legal/hosting-info.schema.json. La Privacy Policy genera da qui la sezione 'Dati di navigazione'. Vive nel .local perché dipende da dove pubblichi. Assente = testo generico; indicato ma mancante o non valido = il frontend non parte.
     */
    hostingInfo?: string;
  };
  /**
   * Configurazione dell'esposizione del container backend. Il backend è normalmente interno alla rete Docker; abilitare 'public' solo per API pubbliche o deploy separato.
   */
  backend?: {
    /**
     * Se true, il backend viene esposto su una porta dell'host (richiede docker-compose.backend-exposed.yml). Default: false.
     */
    public?: boolean;
    /**
     * Porta host su cui esporre il backend (usata solo se 'public: true').
     */
    publicPort?: number | null;
  };
  /**
   * Lingue del sito come codici a due lettere: SORGENTE UNICA, consumata in modo indipendente da entrambe le parti — il backend le arricchisce nelle culture .NET tipizzate (RequestLocalization, messaggi d'errore localizzati), il frontend deriva cultura e formattazione (BCP-47, nomi nativi, giorni) via Intl. Lette anche a build/module-load (routing per-lingua, fallback di pickLocaleText).
   */
  Localization?: {
    /**
     * Lingua di default (codice ISO 639-1, es. 'it'). Deve essere inclusa in SupportedLanguages.
     */
    DefaultLanguage?: string;
    /**
     * Lingue supportate come codici a due lettere. Deve includere DefaultLanguage. Per ognuna serve il catalogo i18n (basic/addon) e i file legali.
     *
     * @minItems 1
     */
    SupportedLanguages?: [string, ...string[]];
  };
  /**
   * Funzioni opzionali dell'Engine accese dal progetto. Committato e senza segreti; voce assente = spenta. Il flag è l'interruttore, la configurazione in global-settings.local.json il requisito: configurazione presente con flag spento = funzione spenta, flag acceso senza configurazione = il backend non parte. Ogni flag vale per frontend e backend insieme: il frontend lo legge a compilazione (login, navbar, sezioni della Privacy Policy), il backend all'avvio (endpoint di login, invio email, segnalazione errori). Valori: true o false senza virgolette; qualunque altra forma ferma il build. Solo in questo file: né in global-settings.local.json né in variabili d'ambiente.
   */
  Features?: {
    /**
     * Login riservato (amministratori): la pagina indicata da loginPage in site.ts esiste ma non è linkata in navbar, e la Privacy Policy non ne parla. Richiede Security.Token.SecretKey.
     */
    Login?: boolean;
    /**
     * Login pubblico: link di login in navbar e sezione dedicata nella Privacy Policy. Vince su Login, che non serve accendere. Richiede Security.Token.SecretKey.
     */
    PublicLogin?: boolean;
    /**
     * Invio email. Richiede Mail.Host e Mail.FromAddress. Accende la sezione dedicata della Privacy Policy.
     */
    Mail?: boolean;
    /**
     * Segnalazione errori via webhook. Richiede ErrorReporting.WebhookUrl. Accende la sezione dedicata della Privacy Policy.
     */
    ErrorReporting?: boolean;
    /**
     * Il sito raccoglie dati personali tramite form (contatti, newsletter, prenotazioni...). Accende la sezione dedicata della Privacy Policy.
     */
    Forms?: boolean;
  };
  /**
   * Sicurezza specifica del progetto: chiavi API, origini CORS, reverse proxy e token JWT. Gli header di sicurezza fissi (uguali per ogni progetto) vivono in security-headers.json, file del template che il progetto figlio non gestisce.
   */
  Security?: {
    /**
     * Configurazione delle API: chiavi accettate e rate limiting.
     */
    ApiConfig?: {
      /**
       * Chiavi API accettate dal backend per le chiamate interne (header X-Api-Key). Il frontend Node SSR usa Security.ApiConfig.Keys[0] per autenticarsi al backend. In produzione usare una stringa casuale di almeno 32 caratteri.
       *
       * @minItems 1
       */
      Keys?: [string, ...string[]];
      /**
       * Rate limiting delle API: soglia globale (per IP) e soglia dedicata al login (POST /auth/login).
       */
      RateLimiting?: {
        /**
         * Attiva/disattiva l'enforcement. Se false, le policy restano registrate ma non contano nulla — utile dietro un WAF/reverse proxy che applica già le proprie soglie.
         */
        Enabled?: boolean;
        /**
         * Limite globale, partizionato per IP client.
         */
        Global?: {
          /**
           * Richieste ammesse per finestra.
           */
          PermitLimit?: number;
          /**
           * Durata della finestra, in secondi.
           */
          WindowSeconds?: number;
        };
        /**
         * Limite su POST /auth/login, partizionato per IP client — pensato per rendere impraticabile il brute force sulle credenziali.
         */
        Login?: {
          /**
           * Richieste ammesse per finestra.
           */
          PermitLimit?: number;
          /**
           * Durata della finestra, in secondi.
           */
          WindowSeconds?: number;
        };
      };
    };
    /**
     * Origini CORS ammesse per il backend. In produzione impostare l'URL completo con schema (es. 'https://miodominio.it'). Lasciare vuoto in sviluppo locale (il backend è interno alla rete Docker).
     */
    CorsOrigins?: string[];
    /**
     * Indica se il backend è dietro un reverse proxy (es. nginx, Cloudflare). Se true, il backend legge l'IP reale da X-Forwarded-For. Impostare a true quando si usa frontend.hostname.
     */
    BehindProxy?: boolean;
    /**
     * Configurazione JWT del login. La SecretKey è il requisito, l'interruttore è Features.Login/PublicLogin (global-settings.json): chiave presente con login spento = login spento; login acceso senza chiave = il backend non parte.
     */
    Token?: {
      /**
       * Chiave segreta per firmare i JWT: almeno 32 byte UTF-8, senza spazi o a capo ai bordi, diversa dal segnaposto dell'esempio. Requisito di Features.Login/PublicLogin; setup.mjs la genera già.
       */
      SecretKey?: string;
      /**
       * Durata in secondi dei token JWT emessi. Default: 3000 (50 minuti).
       */
      ExpirationSeconds?: number;
    };
  };
  /**
   * Configurazione SMTP del mailer dell'engine (EngineMailer). Contiene SEGRETI (password) → vive in global-settings.local.json. Requisito di Features.Mail: il mailer è acceso solo con Features.Mail e Host+FromAddress presenti; spento, ogni invio risponde 503. Features.Mail acceso senza Host/FromAddress = il backend non parte. Volutamente generica (SMTP standard): lo stesso codice spedisce con OVH, Brevo, Mailgun, Amazon SES, Gmail o un relay locale cambiando solo questi valori. Per non finire in spam, FromAddress deve stare sul tuo dominio e vanno configurati i record DNS SPF/DKIM/DMARC.
   */
  Mail?: {
    /**
     * Host del server SMTP. Es. OVH: 'ssl0.ovh.net'.
     */
    Host?: string;
    /**
     * Porta SMTP. 587 (STARTTLS) o 465 (SSL/TLS) nella maggior parte dei casi.
     */
    Port?: number;
    /**
     * Modalità di cifratura del canale (TLS sempre obbligatorio). 'Auto' sceglie in sicurezza dalla porta: 465 -> SslOnConnect, altre -> StartTls (mai connessione in chiaro). 'StartTls' tipico su 587; 'SslOnConnect' tipico su 465; 'None' SOLO per relay locali fidati.
     */
    Security?: "Auto" | "None" | "StartTls" | "SslOnConnect";
    /**
     * Utente SMTP (di solito l'indirizzo completo della casella). Vuoto = invio senza autenticazione (relay aperti/locali).
     */
    Username?: string;
    /**
     * Password SMTP della casella. SEGRETO: tienila solo in global-settings.local.json.
     */
    Password?: string;
    /**
     * Mittente di default (usato quando il chiamante non passa un 'from'). DEVE stare sul tuo dominio: è ciò che fa quadrare SPF/DKIM. Mai l'indirizzo di un visitatore.
     */
    FromAddress?: string;
    /**
     * Nome visualizzato di default del mittente (opzionale).
     */
    FromName?: string;
    /**
     * Timeout di connessione/invio in secondi.
     */
    TimeoutSeconds?: number;
    /**
     * Dimensione massima totale degli allegati per messaggio, in byte. Superata -> errore 413. Default 10485760 (10 MB). 0 = nessun limite (sconsigliato su endpoint pubblici).
     */
    MaxAttachmentBytes?: number;
    /**
     * Se true, prima di inviare verifica via DNS che il dominio dei destinatari possa ricevere posta (record MX, fallback A/AAAA): typo di dominio (gmail.con) e domini inesistenti vengono scartati con 400 senza aprire l'SMTP. NON verifica l'esistenza della casella. Default false: nessuna query DNS se non lo accendi.
     */
    VerifyRecipientDomain?: boolean;
  };
  /**
   * Segnalazione errori dell'engine (IErrorReportingService): un POST JSON verso un webhook esterno per ogni eccezione non applicativa o applicativa con status >=500. Non contiene segreti in senso stretto ma vive comunque in global-settings.local.json perché è pubblicazione/ambiente, non identità del progetto. Volutamente senza SDK di terze parti: un webhook HTTP generico, non l'endpoint proprietario di un vendor. Requisito di Features.ErrorReporting: attivo solo con il flag acceso e WebhookUrl valorizzato.
   */
  ErrorReporting?: {
    /**
     * URL del webhook a cui inviare la segnalazione (POST JSON: message, exceptionType, statusCode, path, method, stackTrace troncato, timestamp). Vuoto con Features.ErrorReporting spento = nessuna chiamata uscente; vuoto con il flag acceso = il backend non parte.
     */
    WebhookUrl?: string;
  };
  /**
   * Qualità della variante web-ottimizzata di un blob immagine (EngineBlobController.webopt). Le DIMENSIONI richiedibili non sono qui: sono una whitelist fissa dell'Engine (`ALLOWED_WIDTHS` in `frontend/src/app/core/engine/asset-config.ts`, rispecchiata lato C# in `EngineBlobController.AllowedWebOptSizes`) — non una scelta per-progetto, sono le stesse larghezze per qualunque sito.
   */
  Media?: {
    /**
     * Qualità WebP (1-100) della variante web-ottimizzata, per ogni dimensione della whitelist fissa dell'Engine.
     */
    WebOptQuality?: number;
  };
  /**
   * Canale realtime SSE (EngineNotificationStreamController, `GET /notifications/stream`).
   */
  Notifications?: {
    /**
     * Intervallo (secondi) del commento di keep-alive che tiene viva la connessione attraverso proxy/idle-timeout. Un reverse proxy/CDN con idle-timeout più corto del default (alcuni tagliano a 15-20s) richiede un valore più basso.
     */
    HeartbeatSeconds?: number;
    /**
     * Delay di riconnessione (secondi) suggerito al browser (campo SSE `retry:`).
     */
    ReconnectDelaySeconds?: number;
  };
  /**
   * Identità ed estetica MINIMA del sito (committabile, del progetto). Iniettata nel frontend al build via environment.ts. Qui c'è un solo colore, `colorTema` (il brand). Tutto il resto dell'aspetto (tono, superfici e pannello, palette, navbar, footer, breadcrumb, movimento, font, og:image, effetto smoke, comportamento per ruolo di pagina) non è un campo di questo file: lo decide il design system attivo (`DesignSystemPreset`), scelto o esteso in site.ts e passato a `shell.designSystem`. `shell` ha solo `designSystem` e `showNotifications`; `isWebApp` è un campo proprio di site.ts; il link di login in navbar lo decide Features.PublicLogin. Il menu di header/footer e l'icona di brand sono dato risolto a runtime in nav.ts.
   */
  site?: {
    /**
     * Descrizione generale del sito, per-lingua: chiavi = tag lingua (come Localization.SupportedLanguages), valori = testo. Usata in meta description SEO, footer e JSON-LD; il build usa la lingua default per i file statici, l'SSR localizza per richiesta. Accettata anche come singola stringa (legacy), normalizzata sulla lingua default.
     */
    description?: {
      [k: string]: string;
    };
    /**
     * Colore tema principale (hex #RGB o #RRGGBB). Genera la palette OKLCH e il tono testo chiaro/scuro.
     */
    colorTema?: string;
  };
  /**
   * Valori aggiuntivi liberi, leggibili da entrambi i progetti senza modificare script o codice infrastrutturale.
   *
   * - Backend (ASP.NET Core): ogni chiave è disponibile tramite IConfiguration["Custom:TuaChiave"] o IConfiguration["Custom:Sezione:SottoChiave"]. Supporta oggetti annidati arbitrari.
   * - Frontend Node SSR: disponibile tramite getBr1Settings().Custom in server-env.ts.
   * - Browser Angular: disponibile tramite inject(APP_CUSTOM) (l'SSR la serializza in TransferState e il browser la rilegge in idratazione). NON metterci segreti: è committabile e ora visibile al client.
   *
   * Esempio:
   *   "Custom": {
   *     "FeatureFlags": { "NuovaFunzione": true },
   *     "Analytics": { "TrackingId": "UA-XXXXX" },
   *     "MaxUploadMb": 10
   *   }
   */
  Custom?: {
    [k: string]: unknown;
  };
}
