using Backend.Models;

namespace Backend.Generators;

/// <summary>
/// Dati condivisi tra tutti i generatori (un tempo <c>data/generators/shared.json</c>):
/// dizionari di parole comuni, gruppi di policy, liste composte e alias di fasce d'età.
/// </summary>
public static class SharedContent
{
    /// <summary>Dizionari di parole comuni (con punteggio opzionale), riusati dai placeholder di ogni generatore.</summary>
    public static Dictionary<string, List<ScoredItem>> FlatLists { get; } = new()
    {
        ["social"] =
        [
            "Instagram",
            "TikTok",
            "Facebook",
            "Twitter (o X)",
            "LinkedIn",
            "YouTube",
            "WhatsApp",
            "Telegram",
        ],
        ["city"] =
        [
            "Ascoli Piceno",
            "Assisi",
            "Asti",
            "Benevento",
            "Bergamo",
            "Brescia",
            "Brindisi",
            "Cosenza",
            "Cremona",
            "Cuneo",
            "Enna",
            "Fermo",
            "Ferrara",
            "Gubbio",
            "Lecce",
            "Lucca",
            "L’Aquila",
            "Macerata",
            "Mantova",
            "Matera",
            "Modena",
            "Orvieto",
            "Otranto",
            "Padova",
            "Parma",
            "Perugia",
            "Piacenza",
            "Potenza",
            "Ragusa",
            "Ravenna",
            "Rieti",
            "Salerno",
            "Siena",
            "Siracusa",
            "Spoleto",
            "Teramo",
            "Trapani",
            "Treviso",
            "Urbino",
            "Viterbo",
        ],
        ["nome-m"] =
        [
            "Adolfo",
            "Agostino",
            "Albino",
            "Aldo",
            "Alfredo",
            "Alvaro",
            "Amedeo",
            "Andrea",
            "Anselmo",
            "Arnaldo",
            "Arturo",
            "Attilio",
            "Bachisio",
            "Basilio",
            "Benito",
            "Bernardo",
            "Biagio",
            "Bonifacio",
            "Bruno",
            "Camillo",
            "Cesare",
            "Ciro",
            "Costantino",
            "Dalmazio",
            "Danilo",
            "Efisio",
            "Egidio",
            "Elio",
            "Ennio",
            "Erminio",
            "Ettore",
            "Eugenio",
            "Eusebio",
            "Fausto",
            "Ferdinando",
            "Franco",
            "Gastone",
            "Gavino",
            "Gennaro",
            "Gervasio",
            "Gianfranco",
            "Giannantonio",
            "Gianni",
            "Gino",
            "Guglielmo",
            "Ido",
            "Ignazio",
            "Innocenzo",
            "Ivano",
            "Lamberto",
            "Leopoldo",
            "Luigi",
            "Mario",
            "Nestore",
            "Onofrio",
            "Orlando",
            "Ottavio",
            "Pasquale",
            "Pietro",
            "Pino",
            "Pio",
            "Raimondo",
            "Rodolfo",
            "Romolo",
            "Sandro",
            "Serafino",
            "Silvio",
            "Tullio",
            "Ugo",
        ],
        ["nome-f"] =
        [
            "Ada",
            "Adele",
            "Amalia",
            "Angela",
            "Antonietta",
            "Assunta",
            "Aurora",
            "Beatrice",
            "Carla",
            "Carmela",
            "Caterina",
            "Clara",
            "Concetta",
            "Deborah",
            "Dorotea",
            "Elena",
            "Elisa",
            "Emilia",
            "Eva",
            "Flora",
            "Francesca",
            "Gemma",
            "Genoveffa",
            "Giovanna",
            "Giulia",
            "Irene",
            "Isabella",
            "Lia",
            "Lucia",
            "Luisa",
            "Margherita",
            "Marisa",
            "Mariuccia",
            "Matilde",
            "Natalia",
            "Olga",
            "Paola",
            "Rosa",
            "Sara",
            "Teresa",
            "Valentina",
            "Vera",
            "Vilma",
            "Vittoria",
            "Zita",
        ],
        ["cognome"] =
        [
            "Barbieri",
            "Bianchi",
            "Caruso",
            "Colombo",
            "Conti",
            "De Angelis",
            "De Luca",
            "Esposito",
            "Ferrara",
            "Ferrari",
            "Ferri",
            "Gallo",
            "Greco",
            "Leone",
            "Lombardi",
            "Mancini",
            "Marchetti",
            "Mariani",
            "Marini",
            "Martini",
            "Messina",
            "Moretti",
            "Palmieri",
            "Pellegrino",
            "Ricci",
            "Rinaldi",
            "Rizzo",
            "Romano",
            "Rossetti",
            "Rossi",
            "Russo",
            "Santoro",
            "Sartori",
            "Serra",
        ],
    };

    /// <summary>Gruppi di tag mutuamente esclusivi referenziabili per nome.</summary>
    public static Dictionary<string, List<string>> PolicyGroups { get; } = new()
    {
        ["eta"] = ["eta-minorenne", "eta-giovane", "eta-cresciuto", "eta-adulto", "eta-anziano"],
        // "identità": età E professione nello stesso gruppo, così un testo definisce il soggetto
        // una sola volta (niente "50 anni, nonno" + "studente universitario" nella stessa descrizione).
        ["identita"] = ["professioni", "eta-minorenne", "eta-giovane", "eta-cresciuto", "eta-adulto", "eta-anziano"],
    };

    /// <summary>Liste derivate, composte concatenando altre FlatLists.</summary>
    public static Dictionary<string, List<string>> ComposedLists { get; } = new()
    {
        ["nome"] = ["nome-m", "nome-f"],
    };

    /// <summary>Mappa alias → range d'età (es. <c>eta-giovane</c> → <c>[18-26]</c>).</summary>
    public static Dictionary<string, string> AgeAliases { get; } = new()
    {
        ["eta-giovane"] = "[18-26]",
        ["eta-cresciuto"] = "[24-44]",
        ["eta-adulto"] = "[35-65]",
        ["eta-anziano"] = "[46-76]",
        ["eta-minorenne"] = "[12-17]",
    };
}
